"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](fg:#d79921)\
$os\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$fill\
$battery\
$time\
[─╮](fg:#d79921)
[╰─](fg:#d79921)$character"""

[fill]
symbol = ' '

[os]
disabled = false
style = "fg:#d79921"

[os.symbols]
Linux = "λ "

[directory]
style = "bold fg:#d79921"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"pictures" = " "

[git_branch]
symbol = " "
style = "fg:#b8bb26"
format = '[[ $symbol$branch](fg:#b8bb26)]($style)'

[git_status]
style = "fg:#fb4934"
format = '[[($all_status$ahead_behind)](fg:#fb4934)]($style)'

[python]
symbol = " "
style = "fg:#fabd2f"
format = '[[ $symbol$version](fg:#fabd2f)]($style)'

[nodejs]
symbol = " "
style = "fg:#b8bb26"
format = '[[ $symbol$version](fg:#b8bb26)]($style)'

[rust]
symbol = " "
style = "fg:#fb4934"
format = '[[ $symbol$version](fg:#fb4934)]($style)'

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰁽 "
empty_symbol = "󰂎 "
format = '[$symbol$percentage]($style) '

[[battery.display]]
threshold = 20
style = "bold fg:#fb4934"

[[battery.display]]
threshold = 50
style = "fg:#fabd2f"

[[battery.display]]
threshold = 100
style = "fg:#b8bb26"

[time]
disabled = false
time_format = "%H:%M"
style = "fg:#928374"
format = '[ $time]($style) '

[character]
success_symbol = '[❯](bold fg:#b8bb26)'
error_symbol = '[❯](bold fg:#fb4934)'
