-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(7a5230)",
			inactive_border = "rgb(6e5834)",
		},
	},
	group = {
		col = {
			border_active = "rgb(7a5230)",
			border_inactive = "rgb(6e5834)",
			border_locked_active = "rgb(a94a38)",
			border_locked_inactive = "rgb(6e5834)",
		},
		groupbar = {
			col = {
				active = "rgb(7a5230)",
				inactive = "rgb(6e5834)",
				locked_active = "rgb(a94a38)",
				locked_inactive = "rgb(6e5834)",
			},
		},
	},
})
