-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Bibata-Original-Amber")
hl.env("XCURSOR_THEME", "Bibata-Original-Amber")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")
